'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar de My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("13")>  _
        Public Property margen() As Single
            Get
                Return CType(Me("margen"),Single)
            End Get
            Set
                Me("margen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("16")>  _
        Public Property iva() As Single
            Get
                Return CType(Me("iva"),Single)
            End Get
            Set
                Me("iva") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.5")>  _
        Public Property comision() As Single
            Get
                Return CType(Me("comision"),Single)
            End Get
            Set
                Me("comision") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Recordar() As Boolean
            Get
                Return CType(Me("Recordar"),Boolean)
            End Get
            Set
                Me("Recordar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserName() As String
            Get
                Return CType(Me("UserName"),String)
            End Get
            Set
                Me("UserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property pw() As String
            Get
                Return CType(Me("pw"),String)
            End Get
            Set
                Me("pw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property periodoVta_pedidos() As Decimal
            Get
                Return CType(Me("periodoVta_pedidos"),Decimal)
            End Get
            Set
                Me("periodoVta_pedidos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ncaja() As Byte
            Get
                Return CType(Me("ncaja"),Byte)
            End Get
            Set
                Me("ncaja") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property mnu_tablas() As Boolean
            Get
                Return CType(Me("mnu_tablas"),Boolean)
            End Get
            Set
                Me("mnu_tablas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property menus() As String
            Get
                Return CType(Me("menus"),String)
            End Get
            Set
                Me("menus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Mcatalogo() As Boolean
            Get
                Return CType(Me("Mcatalogo"),Boolean)
            End Get
            Set
                Me("Mcatalogo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property solocaja() As Boolean
            Get
                Return CType(Me("solocaja"),Boolean)
            End Get
            Set
                Me("solocaja") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("22")>  _
        Public ReadOnly Property LineasXfactura() As Integer
            Get
                Return CType(Me("LineasXfactura"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property impresora_ticket() As String
            Get
                Return CType(Me("impresora_ticket"),String)
            End Get
            Set
                Me("impresora_ticket") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property impresora_factura() As String
            Get
                Return CType(Me("impresora_factura"),String)
            End Get
            Set
                Me("impresora_factura") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Impresora_reportes() As String
            Get
                Return CType(Me("Impresora_reportes"),String)
            End Get
            Set
                Me("Impresora_reportes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property almacen() As Integer
            Get
                Return CType(Me("almacen"),Integer)
            End Get
            Set
                Me("almacen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ftp.casabaroudi.com")>  _
        Public Property ftpserver() As String
            Get
                Return CType(Me("ftpserver"),String)
            End Get
            Set
                Me("ftpserver") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("casabaroud")>  _
        Public Property ftpuser() As String
            Get
                Return CType(Me("ftpuser"),String)
            End Get
            Set
                Me("ftpuser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DXmtVV6hErrR")>  _
        Public Property ftppw() As String
            Get
                Return CType(Me("ftppw"),String)
            End Get
            Set
                Me("ftppw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Autoriza_Automatico() As Boolean
            Get
                Return CType(Me("Autoriza_Automatico"),Boolean)
            End Get
            Set
                Me("Autoriza_Automatico") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/domains/casabaroudi.com/public_html/net/cortes/")>  _
        Public Property ftppath_cortes() As String
            Get
                Return CType(Me("ftppath_cortes"),String)
            End Get
            Set
                Me("ftppath_cortes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property mostrar_web() As Boolean
            Get
                Return CType(Me("mostrar_web"),Boolean)
            End Get
            Set
                Me("mostrar_web") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property puedeAutorizar() As Boolean
            Get
                Return CType(Me("puedeAutorizar"),Boolean)
            End Get
            Set
                Me("puedeAutorizar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\tmp\mio.tmp")>  _
        Public Property tmpfile() As String
            Get
                Return CType(Me("tmpfile"),String)
            End Get
            Set
                Me("tmpfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Unchecked")>  _
        Public Property id_grupo() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("id_grupo"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("id_grupo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Checked")>  _
        Public Property Grupo() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("Grupo"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("Grupo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Checked")>  _
        Public Property PZ_x_Caja() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("PZ_x_Caja"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("PZ_x_Caja") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Checked")>  _
        Public Property Pz_X_Exhibidor() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("Pz_X_Exhibidor"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("Pz_X_Exhibidor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Unchecked")>  _
        Public Property Exhi_x_caja() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("Exhi_x_caja"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("Exhi_x_caja") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Checked")>  _
        Public Property Costo_x_pz() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("Costo_x_pz"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("Costo_x_pz") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Unchecked")>  _
        Public Property Costo_x_Exhi() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("Costo_x_Exhi"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("Costo_x_Exhi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Checked")>  _
        Public Property Pv_Pieza() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("Pv_Pieza"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("Pv_Pieza") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Checked")>  _
        Public Property pv_exhibidor() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("pv_exhibidor"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("pv_exhibidor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Unchecked")>  _
        Public Property pv_caja() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("pv_caja"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("pv_caja") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Checked")>  _
        Public Property costo_x_caja() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("costo_x_caja"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("costo_x_caja") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Cobrar_tarjeta() As Boolean
            Get
                Return CType(Me("Cobrar_tarjeta"),Boolean)
            End Get
            Set
                Me("Cobrar_tarjeta") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Checked")>  _
        Public Property pedidos_calcular() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("pedidos_calcular"),Global.System.Windows.Forms.CheckState)
            End Get
            Set
                Me("pedidos_calcular") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("150")>  _
        Public Property grupo_suspendidos() As String
            Get
                Return CType(Me("grupo_suspendidos"),String)
            End Get
            Set
                Me("grupo_suspendidos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11")>  _
        Public Property iva2() As Single
            Get
                Return CType(Me("iva2"),Single)
            End Get
            Set
                Me("iva2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property lineasnc() As String
            Get
                Return CType(Me("lineasnc"),String)
            End Get
            Set
                Me("lineasnc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property impresora_default() As Boolean
            Get
                Return CType(Me("impresora_default"),Boolean)
            End Get
            Set
                Me("impresora_default") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property auto_open_inventario() As Boolean
            Get
                Return CType(Me("auto_open_inventario"),Boolean)
            End Get
            Set
                Me("auto_open_inventario") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property recalcularprecios() As Boolean
            Get
                Return CType(Me("recalcularprecios"),Boolean)
            End Get
            Set
                Me("recalcularprecios") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property terminal() As Boolean
            Get
                Return CType(Me("terminal"),Boolean)
            End Get
            Set
                Me("terminal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("file://\\abarroterabara\datosintegral\datos_sistema\logo.jpg")>  _
        Public Property logo() As String
            Get
                Return CType(Me("logo"),String)
            End Get
            Set
                Me("logo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("487,477,526,519,245")>  _
        Public Property excluirprovedores() As String
            Get
                Return CType(Me("excluirprovedores"),String)
            End Get
            Set
                Me("excluirprovedores") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12.2")>  _
        Public Property tipodecambio() As Single
            Get
                Return CType(Me("tipodecambio"),Single)
            End Get
            Set
                Me("tipodecambio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FEI_activo() As Boolean
            Get
                Return CType(Me("FEI_activo"),Boolean)
            End Get
            Set
                Me("FEI_activo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("cfd@casabaroudi.com")>  _
        Public Property mimail() As String
            Get
                Return CType(Me("mimail"),String)
            End Get
            Set
                Me("mimail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1,2,3,4,5,6")>  _
        Public Property kagentes() As String
            Get
                Return CType(Me("kagentes"),String)
            End Get
            Set
                Me("kagentes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("NA")>  _
        Public Property ncargo() As String
            Get
                Return CType(Me("ncargo"),String)
            End Get
            Set
                Me("ncargo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property separar() As Boolean
            Get
                Return CType(Me("separar"),Boolean)
            End Get
            Set
                Me("separar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/public_html/net/fei/")>  _
        Public Property ftpfei() As String
            Get
                Return CType(Me("ftpfei"),String)
            End Get
            Set
                Me("ftpfei") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString)>  _
        Public ReadOnly Property AdmintegralConnectionString() As String
            Get
                Return CType(Me("AdmintegralConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=CASABAROUDI\COMPAC;Initial Catalog=integra;Persist Security Info=True"& _ 
            ";User ID=sa;Password=C0ntpaq$")>  _
        Public ReadOnly Property AdminTegral() As String
            Get
                Return CType(Me("AdminTegral"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=CASABAROUDI\COMPAC;Initial Catalog=integra;Persist Security Info=True"& _ 
            ";User ID=sa;Password=C0ntpaq$")>  _
        Public ReadOnly Property integraConnectionString() As String
            Get
                Return CType(Me("integraConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=CASABAROUDI\COMPAC;Initial Catalog=SAT;Persist Security Info=True;Use"& _ 
            "r ID=sa;Password=C0ntpaq$")>  _
        Public ReadOnly Property SAT_catalogosConnectionString() As String
            Get
                Return CType(Me("SAT_catalogosConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=CASABAROUDI\COMPAC;Initial Catalog=integra;Persist Security Info=True"& _ 
            ";User ID=sa;Password=C0ntpaq$")>  _
        Public Property sqlserver() As String
            Get
                Return CType(Me("sqlserver"),String)
            End Get
            Set
                Me("sqlserver") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=CASABAROUDI\COMPAC;Initial Catalog=SAT;Persist Security Info=True;Use"& _ 
            "r ID=sa;Password=C0ntpaq$")>  _
        Public Property sqlsat() As String
            Get
                Return CType(Me("sqlsat"),String)
            End Get
            Set
                Me("sqlsat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property items_adicionales() As String
            Get
                Return CType(Me("items_adicionales"),String)
            End Get
            Set
                Me("items_adicionales") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.AdminTegral.My.MySettings
            Get
                Return Global.AdminTegral.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
